services:
  postgres:
    image: postgres:latest
    container_name: pizzeria-postgres
    environment:
      POSTGRES_USER: pizzeria
      POSTGRES_PASSWORD: pizzeria
      POSTGRES_DB: pizzeria
    ports:
      - "5433:5432"  # Zmiana na standardowy port PostgreSQL
    networks:
      - pizzeria-network
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pizzeria"]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - ./src/main/java/org/localhost/pizzeria/messaging/config/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./src/main/java/org/localhost/pizzeria/messaging/config/definitions.json:/etc/rabbitmq/definitions.json
    container_name: pizzeria-rabbitmq
    ports:
      - "5672:5672"   # AMQP port
      - "15672:15672" # Management UI
    networks:
      - pizzeria-network
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "check_port_connectivity" ]
      interval: 30s
      timeout: 10s
      retries: 3

  nats:
    image: nats:2.10-alpine
    container_name: pizzeria-nats
    restart: unless-stopped
    ports:
      - "4222:4222"     # Client connections
      - "6222:6222"     # Clustering
      - "8222:8222"     # HTTP Management
    command:
      - "-js"           # Włączamy JetStream
      - "-m"           # Włączamy monitoring
      - "8222"         # Port monitoringu
    networks:
      - pizzeria-network
    healthcheck:
      test: ["CMD", "/nats-server", "--help"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  pizzeria-network:
    driver: bridge

volumes:
  postgres_data:
  rabbitmq_data: