spring:
  profiles:
    active: dev
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

rabbitmq:
  queue:
    supply-check: supply-check-queue
  exchange:
    supply-check: supply-check-exchange
  routing-key:
    supply-check: supply-check-routing-key


nats:
  url: "nats://localhost:4222"
