spring:
  profiles:
    active: dev
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

rabbitmq:
  queue:
    supply-check: supply-check-queue
    supply-check-dlq: supply-check-dlq
  exchange:
    supply-check: supply-check-exchange
    supply-check-dlq-exchange: supply-check-dlq-exchange
  routing-key:
    supply-check: supply-check-routing-key
    supply-check-dead-letter-routing-queue: supply-check-dead-letter-routing-key

scheduler:
  supply-check:
    interval: 100000

nats:
  url: "nats://localhost:4222"